services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - "10000:10000"  # Blob Storage
      - "10001:10001"  # Queue Storage
      - "10002:10002"  # Table Storage
    environment:
      AZURITE_ACCOUNTS: "devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==:http://0.0.0.0:10000/devstoreaccount1"
      AZURITE_LOOSE_AUTH_MODE: "true"
    volumes:
      - azurite-data:/data
    command: "azurite --silent --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --debug /data/debug.log --loose --skipApiVersionCheck"
    networks:
      - elysium-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - elysium-network

  # Set up MinIO buckets during initialization
  minio-setup:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/revelare-vessel-data;
      /usr/bin/mc policy set download minio/revelare-vessel-data;
      exit 0;
      "
    networks:
      - elysium-network

  # FTP server for vessel data
  ftp-server:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"         # FTP control
      - "21000-21010:21000-21010"  # Passive port range
    environment:
      USERS: "ftpuser|ftppass"
      ADDRESS: localhost
      PASSIVE_PORTS: 21000-21010
    volumes:
      - ftp-data:/home/ftpuser
    networks:
      - elysium-network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "vsftpd"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Initialize Azure Storage
  azure-setup:
    image: mcr.microsoft.com/azure-cli:latest
    depends_on:
      - azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;"
    entrypoint: >
      /bin/bash -c '
      echo "Waiting for Azurite to start...";
      sleep 10;
      echo "Creating blob container and queues...";
      az storage container create --name usvdata --connection-string "$AZURE_STORAGE_CONNECTION_STRING";
      az storage queue create --name validation-queue --connection-string "$AZURE_STORAGE_CONNECTION_STRING";
      az storage queue create --name transfer-queue --connection-string "$AZURE_STORAGE_CONNECTION_STRING";
      az storage queue create --name cleanup-queue --connection-string "$AZURE_STORAGE_CONNECTION_STRING";
      echo "Azure storage setup completed";
      '
    networks:
      - elysium-network

networks:
  elysium-network:
    driver: bridge

volumes:
  azurite-data:
  minio-data:
  ftp-data: