version: '3'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.18.0  # Try an older version
    ports:
      - "10000:10000"  # Blob storage
      - "10001:10001"  # Queue storage
      - "10002:10002"  # Table storage
    volumes:
      - azurite-data:/data
    command: "azurite --silent --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data"
    environment:
      # Setting loose permissions for development
      AZURITE_ACCOUNTS: "devstoreaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==:http://0.0.0.0:10000/devstoreaccount1"
      AZURITE_LOOSE_AUTH_MODE: "true"  # Add this to try loose auth mode

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio-data:/data
    command: "server /data --console-address :9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/revelare-vessel-data;
      /usr/bin/mc policy set public myminio/revelare-vessel-data;
      exit 0;
      "

volumes:
  azurite-data:
  minio-data: